ERROR:root:
Traceback (most recent call last):
  File "D:/Institute/United International University/Spring 2019/Thesis and Project/Projects/scrapingWeb/venv/upscraping.py", line 10, in <module>
    raise Exception
Exception
ERROR:root:
Traceback (most recent call last):
  File "D:\Institute\United International University\Spring 2019\Thesis and Project\Projects\scrapingWeb\venv\upscraping.py", line 14, in <module>
    raise Exception
Exception
ERROR:root:
Traceback (most recent call last):
  File "D:\Institute\United International University\Spring 2019\Thesis and Project\Projects\scrapingWeb\venv\upscraping.py", line 14, in <module>
    raise Exception
Exception
ERROR:root:
Traceback (most recent call last):
  File "D:\Institute\United International University\Spring 2019\Thesis and Project\Projects\scrapingWeb\venv\upscraping.py", line 14, in <module>
    raise Exception
Exception
ERROR:root:[Errno 2] No such file or directory: 'html/aj.html'
Traceback (most recent call last):
  File "D:\Institute\United International University\Spring 2019\Thesis and Project\Projects\scrapingWeb\venv\upscraping.py", line 32, in write_webpage_as_html
    with open(filepath, 'wb') as fobj:
FileNotFoundError: [Errno 2] No such file or directory: 'html/aj.html'
ERROR:root:[Errno 2] No such file or directory: 'html/aj.html'
Traceback (most recent call last):
  File "D:\Institute\United International University\Spring 2019\Thesis and Project\Projects\scrapingWeb\venv\upscraping.py", line 43, in read_webpage_from_html
    with open(filepath) as fobj:
FileNotFoundError: [Errno 2] No such file or directory: 'html/aj.html'
ERROR:root:<urlopen error [Errno 11002] getaddrinfo failed>
Traceback (most recent call last):
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 1152, in _send_request
    self.endheaders(body)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 934, in _send_output
    self.send(msg)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 877, in send
    self.connect()
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\socket.py", line 694, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Institute\United International University\Spring 2019\Thesis and Project\Projects\scrapingWeb\venv\upscraping.py", line 21, in retrieve_webpage
    html = urlopen(self.__url)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 466, in open
    response = self._open(req, data)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 484, in _open
    '_open', req)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11002] getaddrinfo failed>
ERROR:root:a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "D:\Institute\United International University\Spring 2019\Thesis and Project\Projects\scrapingWeb\venv\upscraping.py", line 36, in write_webpage_as_html
    fobj.write(self.__data)
TypeError: a bytes-like object is required, not 'str'
ERROR:root:invalid mode: 'ws'
Traceback (most recent call last):
  File "D:\Institute\United International University\Spring 2019\Thesis and Project\Projects\scrapingWeb\venv\upscraping.py", line 32, in write_webpage_as_html
    with open(filepath, 'ws') as fobj:
ValueError: invalid mode: 'ws'
ERROR:root:write() argument must be str, not bytes
Traceback (most recent call last):
  File "D:\Institute\United International University\Spring 2019\Thesis and Project\Projects\scrapingWeb\venv\upscraping.py", line 36, in write_webpage_as_html
    fobj.write(self.__data)
TypeError: write() argument must be str, not bytes
ERROR:root:<urlopen error [Errno 11002] getaddrinfo failed>
Traceback (most recent call last):
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 1152, in _send_request
    self.endheaders(body)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 934, in _send_output
    self.send(msg)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 877, in send
    self.connect()
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\socket.py", line 694, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Institute\United International University\Spring 2019\Thesis and Project\Projects\scrapingWeb\venv\upscraping.py", line 21, in retrieve_webpage
    html = urlopen(self.__url)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 466, in open
    response = self._open(req, data)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 484, in _open
    '_open', req)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11002] getaddrinfo failed>
ERROR:root:write() argument must be str, not bytes
Traceback (most recent call last):
  File "D:\Institute\United International University\Spring 2019\Thesis and Project\Projects\scrapingWeb\venv\upscraping.py", line 37, in write_webpage_as_html
    fobj.write(self.__data)
TypeError: write() argument must be str, not bytes
ERROR:root:'charmap' codec can't decode byte 0x8d in position 16272: character maps to <undefined>
Traceback (most recent call last):
  File "D:\Institute\United International University\Spring 2019\Thesis and Project\Projects\scrapingWeb\venv\upscraping.py", line 45, in read_webpage_from_html
    self.__data = fobj.read()
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 16272: character maps to <undefined>
ERROR:root:'charmap' codec can't decode byte 0x8d in position 16272: character maps to <undefined>
Traceback (most recent call last):
  File "D:\Institute\United International University\Spring 2019\Thesis and Project\Projects\scrapingWeb\venv\upscraping.py", line 45, in read_webpage_from_html
    self.__data = fobj.read()
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 16272: character maps to <undefined>
ERROR:root:'charmap' codec can't decode byte 0x8d in position 16272: character maps to <undefined>
Traceback (most recent call last):
  File "D:\Institute\United International University\Spring 2019\Thesis and Project\Projects\scrapingWeb\venv\upscraping.py", line 45, in read_webpage_from_html
    self.__data = fobj.read()
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 16272: character maps to <undefined>
ERROR:root:a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "D:\Institute\United International University\Spring 2019\Thesis and Project\Projects\scrapingWeb\venv\upscraping.py", line 37, in write_webpage_as_html
    fobj.write(self.__data)
TypeError: a bytes-like object is required, not 'str'
ERROR:root:a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "D:\Institute\United International University\Spring 2019\Thesis and Project\Projects\scrapingWeb\venv\upscraping.py", line 37, in write_webpage_as_html
    fobj.write(self.__data)
TypeError: a bytes-like object is required, not 'str'
ERROR:root:a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "D:\Institute\United International University\Spring 2019\Thesis and Project\Projects\scrapingWeb\venv\upscraping.py", line 37, in write_webpage_as_html
    fobj.write(self.__data)
TypeError: a bytes-like object is required, not 'str'
ERROR:root:a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "D:\Institute\United International University\Spring 2019\Thesis and Project\Projects\scrapingWeb\venv\upscraping.py", line 37, in write_webpage_as_html
    fobj.write(self.__data)
TypeError: a bytes-like object is required, not 'str'
ERROR:root:a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "D:\Institute\United International University\Spring 2019\Thesis and Project\Projects\scrapingWeb\venv\upscraping.py", line 37, in write_webpage_as_html
    fobj.write(self.__data)
TypeError: a bytes-like object is required, not 'str'
ERROR:root:a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "D:\Institute\United International University\Spring 2019\Thesis and Project\Projects\scrapingWeb\venv\upscraping.py", line 37, in write_webpage_as_html
    fobj.write(self.__data)
TypeError: a bytes-like object is required, not 'str'
